"""empty message

Revision ID: 619182041b86
Revises: ee31ee243245
Create Date: 2026-04-27 01:53:30.750455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619182041b86'
down_revision = 'ee31ee243245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sellerId', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('product_seller_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sellerId'], ['id'])
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('product_seller_id_fkey'), 'user', ['seller_id'], ['id'])
        batch_op.drop_column('sellerId')

    # ### end Alembic commands ###
