"""fix_camelcase_final

Revision ID: ee31ee243245
Revises: 
Create Date: 2026-04-27 00:28:40.063751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee31ee243245'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('priceUsd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stockQuantity', sa.Integer(), nullable=True),
    sa.Column('categoryId', sa.Integer(), nullable=True),
    sa.Column('yearStart', sa.Integer(), nullable=True),
    sa.Column('yearEnd', sa.Integer(), nullable=True),
    sa.Column('vehicleType', sa.String(length=50), nullable=True),
    sa.Column('isOriginal', sa.Boolean(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['category.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['productId'], ['id'])

    with op.batch_alter_table('compatibility', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'product', ['productId'], ['id'])

    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('password_history_userId_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('userId')
        batch_op.drop_column('createdAt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('password_history_userId_fkey'), 'user', ['userId'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('compatibility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('product')
    # ### end Alembic commands ###
